### ISSUE TITLE
create, key: SAI_OBJECT_TYPE_LAG_MEMBER:oid:0x1a0000000005b7, status: SAI_STATUS_FAILURE

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-swss#199] opened 2017-04-28 02:31 UTC
```
Apr 27 17:07:10.766478 str-msn2700-04 WARNING kernel: [ 2065.173842] sx_netdev_handle_pude_event: Called for logical port - 10F00 status DOWN
Apr 27 17:07:10.770758 str-msn2700-04 INFO kernel: [ 2065.174235] Vlan1000: port 5(Ethernet92) entered disabled state
Apr 27 17:07:10.0 str-msn2700-04 NOTICE orchagent: :- doPortTask: Set port Ethernet92 admin status to up
Apr 27 17:07:10.0 str-msn2700-04 NOTICE orchagent: :- doPortTask: Set port Ethernet92 admin status to up
Apr 27 17:07:10.0 str-msn2700-04 NOTICE orchagent: :- doPortTask: Set port Ethernet92 admin status to up
Apr 27 17:07:10.0 str-msn2700-04 NOTICE orchagent: :- on_port_state_change: Get port state change notification id:1000000000008 status:2
Apr 27 17:07:10.0 str-msn2700-04 NOTICE orchagent: :- setHostIntfsOperStatus: Set operation status DOWN to host interface Ethernet92
Apr 27 17:07:32.026510 str-msn2700-04 INFO ansible-<stdin>: Invoked with ip_path=/sbin/ip
Apr 27 17:07:53.0 str-msn2700-04 ERR syncd: :- handle_generic: failed to create -1
Apr 27 17:07:53.0 str-msn2700-04 NOTICE orchagent: :- handle_switch_shutdown_request: switch shutdown request
Apr 27 17:07:53.0 str-msn2700-04 ERR orchagent: :- on_switch_shutdown_request: Syncd stopped
Apr 27 17:07:53.0 str-msn2700-04 ERR syncd: :- processEvent: failed to execute api: create, key: SAI_OBJECT_TYPE_LAG_MEMBER:oid:0x1a0000000005b7, status: SAI_STATUS_FAILURE
Apr 27 17:07:53.753585 str-msn2700-04 INFO swss.sh[2631]: terminate called without an active exception
```

**Comment by lguohan** [comment] 2017-04-28 02:31
admin@str-msn2700-04:/var/log$ show version

SONiC Software Version: SONiC.HEAD.229-03cd2ce
Distribution: Debian 8.7
Kernel: 3.16.0-4-amd64
Build commit: 03cd2ce
Build date: Thu Apr 27 14:00:42 UTC 2017
Built by: build@jenkins-worker-internal-1

Docker images:
REPOSITORY                TAG                 IMAGE ID            SIZE
docker-orchagent-mlnx     latest              0738a79df4f0        252.8 MB
docker-syncd-mlnx         latest              2c020831585f        402.6 MB
docker-dhcp-relay         latest              750f172b783f        248.5 MB
docker-database           latest              50a68937a2a9        216.4 MB
docker-snmp-sv2           latest              eb99ee7a4007        289.9 MB
docker-teamd              latest              5d52797e6f3e        250.3 MB
docker-platform-monitor   latest              bc1a67348608        273.5 MB
docker-lldp-sv2           latest              23543819565a        254.9 MB
docker-fpm-quagga         latest              e539e95e7318        256.9 MB

**Comment by lguohan** [comment] 2017-04-28 02:40
[sairedis.2017-04-27.16_33_29.466734.txt](https://github.com/Azure/sonic-swss/files/963325/sairedis.2017-04-27.16_33_29.466734.txt)

**Comment by lguohan** [comment] 2017-04-28 02:43
[syncd.txt](https://github.com/Azure/sonic-swss/files/963329/syncd.txt)

**Comment by lguohan** [comment] 2017-04-28 02:45
```
admin@str-msn2700-04:~$ docker exec -it syncd bash
root@str-msn2700-04:/# dpkg --list | grep mlnx
ii  applibs                    1.mlnx.4.2.3102          amd64        Userspace libraries and applications to manage SX devices.
ii  applibs-dev                1.mlnx.4.2.3102          amd64        Header files for applibs.
ii  iproute2                   1.mlnx.4.2.3102          amd64        networking and traffic control tools
ii  iproute2-dev               1.mlnx.4.2.3102          amd64        networking and traffic control tools - development files
ii  mlnx-sai                   1.mlnx.161120            amd64        contains SAI implementation for Mellanox hardware
ii  python-sdk-api             1.mlnx.4.2.3102          amd64        SX SDK API python wrapper module for SX devices.
ii  sx-complib                 1.mlnx.4.2.3102          amd64        Libraries for SX device management
ii  sx-complib-dev             1.mlnx.4.2.3102          amd64        Development files for the sx_complib libraries
ii  sx-complib-dev-static      1.mlnx.4.2.3102          amd64        Static development files for the sx_complib libraries
ii  sx-examples                1.mlnx.4.2.3102          amd64        SX examples for SX devices.
ii  sx-examples-dev            1.mlnx.4.2.3102          amd64        Header files for sx-examples.
ii  sx-gen-utils               1.mlnx.4.2.3102          amd64        Userspace libraries and applications to manage SX devices.
ii  sx-gen-utils-dev           1.mlnx.4.2.3102          amd64        Header files for sx_gen_utils.
ii  sx-scew                    1.mlnx.4.2.3102          amd64        This package adds sx_scew 1.1.2 libraries required for sx_examples
ii  sx-scew-dev                1.mlnx.4.2.3102          amd64        Development files for the sx_scew 1.1.2 libraries
ii  sx-scew-dev-static         1.mlnx.4.2.3102          amd64        Static development files for the sx_scew libraries
ii  sxd-libs                   1.mlnx.4.2.3102          amd64        This package adds libraries needed to manage a SX device:
ii  sxd-libs-dev               1.mlnx.4.2.3102          amd64        Development files for the sxd_libs libraries
ii  sxd-libs-dev-static        1.mlnx.4.2.3102          amd64        Static development files for the sx_complib libraries
```

**Comment by oleksandrivantsiv** [comment] 2017-04-28 17:31
Issue caused by recent update of Mellanox SAI. We temporary moving back to previous version. Fix for the issue will be provided on Wednesday.

**Comment by marian-pritsak** [comment] 2017-05-12 07:18
Fixed in https://github.com/Azure/sonic-buildimage/pull/593

**Comment by marian-pritsak** [comment] 2017-05-15 08:37
Issue still not fixed

**Comment by stcheng** [comment] 2017-10-04 00:08
@marian-pritsak is this fixed?

**Comment by marian-pritsak** [comment] 2017-10-04 09:00
Issue was resolved. Closing...

**Closed by marian-pritsak** 2017-10-04 09:00 UTC
Labels: bug
